#SPDX-License-Identifier: MIT-0
---
# defaults file for dnf_fastestmirror

# dnf_fastestmirror_enable: Whether to enable fastestmirror in DNF
dnf_fastestmirror_enable: true

# dnf_fastestmirror_config_file: Path to DNF configuration file
dnf_fastestmirror_config_file: "/etc/dnf/dnf.conf"

# dnf_fastestmirror_value: Value to set for fastestmirror (0=disabled, 1=enabled)
dnf_fastestmirror_value: "1"
